CREATE TABLE group_share_permissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    share_type VARCHAR(50) NOT NULL,
    enabled    BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_gsp_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_gsp_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_gsp_group_user_type UNIQUE (group_id, user_id, share_type)
);