CREATE TABLE bank_account_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO bank_account_types (id, name)
VALUES (1, 'Corrente'),
       (2, 'Poupança'),
       (3, 'Salário'),
       (4, 'Investimento');

ALTER TABLE bank_account_types
    ALTER COLUMN id RESTART WITH 5;

CREATE TABLE benefit_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO benefit_types (id, name)
VALUES (1, 'Vale-Alimentação'),
       (2, 'Vale-Refeição'),
       (3, 'Premiação');

ALTER TABLE benefit_types
    ALTER COLUMN id RESTART WITH 4;

CREATE TABLE card_brands
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO card_brands (id, name)
VALUES (1, 'Visa'),
       (2, 'Mastercard'),
       (3, 'Elo'),
       (4, 'American Express'),
       (5, 'Hipercard');

ALTER TABLE card_brands
    ALTER COLUMN id RESTART WITH 6;