CREATE TABLE legal_entities
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj               VARCHAR(14)  NOT NULL,
    corporate_name     VARCHAR(255) NOT NULL,
    trade_name         VARCHAR(255),
    state_registration VARCHAR(50)
);